package nl.emilvdijk.quizwebgame.repository;

import java.util.List;
import nl.emilvdijk.quizwebgame.entity.Question;
import nl.emilvdijk.quizwebgame.enums.ApiChoiceEnum;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * JpaRepository class for Question class. implements several derived query generated methods.
 * implements JpaSpecificationExecutor to query by specification. several specification methods have
 * been written in the Question class.
 *
 * @see <a href="https://docs.spring.io/spring-data/jpa/reference/jpa/query-methods.html">spring *
 *     documentation about derived query methods</a>
 * @see <a href="https://docs.spring.io/spring-data/jpa/reference/jpa/specifications.html">spring
 *     Specifications documentation</a>
 * @see Question
 * @author Emil van Dijk
 */
@Repository
public interface QuestionRepo
    extends JpaRepository<Question, Long>, JpaSpecificationExecutor<Question> {

  /**
   * finds all questions excluding questions with id of the given list. this is a method generated
   * by spring
   *
   * @see <a href="https://docs.spring.io/spring-data/jpa/reference/jpa/query-methods.html">spring
   *     documentation about derived query methods</a>
   * @param idList list of questions ids to exclude
   * @return all questions which conform to the criteria
   */
  List<Question> findByIdNotIn(List<Long> idList);

  /**
   * finds all questions excluding questions with id of the given list which also have the same
   * origin as the origin given. this is a method generated by spring
   *
   * @see <a href="https://docs.spring.io/spring-data/jpa/reference/jpa/query-methods.html">spring
   *     documentation about derived query methods</a>
   * @param myIdList list of questions ids to exclude
   * @param origin origin of the desired questions
   * @return all questions which conform to the criteria
   */
  List<Question> findByIdNotInAndOrigin(List<Long> myIdList, ApiChoiceEnum origin);
}
